blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>/', views.detail, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include # < here

from blog.views import home # < here

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')), # < here
    path('', home, name='home') # < here
]

blog/models.py
from django.db import models
from django.urls import reverse # < here
from django.utils.text import slugify # < here


class Post(models.Model): # < here
    title = models.CharField(max_length=255,
                             default='',
                             blank=True)
    body = models.TextField(default='',
                            blank=True)
    slug = models.SlugField(max_length=255,
                            default='',
                            blank=True,
                            unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail',
                       args=[str(self.slug)])

blog/views.py
from django.shortcuts import render
from blog.models import Post # < here


def index(request, slug=None): # < here
    posts = Post.objects.all()
    return render(request,
                  'blog/index.html',
                  {
                      'posts': posts,
                      'section': 'blog_index'
                  })


def detail(request, slug=None): # < here
    post = Post.objects.get(slug=slug)
    return render(request,
                  'blog/detail.html',
                  {
                      'post': post,
                      'section': 'blog_detail'
                  })


def home(request): # < here
    return render(request,
                  'home.html',
                  {'section': 'home'})

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>MySite</title>
</head>
<body>

<div class="main">

    <div class="header">
        <ul class="menu">
            <li class="menu-li">
                <a class="menu-li-a {% if section == 'home' %} menu-li-a-active{% endif %}" href="{% url 'home' %}">Home</a>
            </li>
            <li class="menu-li">
                <a class="menu-li-a {% if section == 'blog_index' %} menu-li-a-active{% endif %}" href="{% url 'blog:index' %}">Blog</a>
            </li>
        </ul>
    </div>

    <div class="content">

        <h1>{% block title %}Default heading{% endblock %}</h1>

        {% block content %}Default content{% endblock %}

    </div>

</div>

</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{ post }}{% endblock %}

{% block content %}{{ post.body }}{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}

{% block title %}Blog index{% endblock %}

{% block content %}

    {% for post in posts %}
        [ {{ post.pk }} ]
        <a href="{{ post.get_absolute_url }}">
            {{ post }}
        </a>
        <br>
    {% endfor %}

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}Home content{% endblock %}